-- Migration 005: immutable, snapshot-backed directory statistics
--
-- Run once in Supabase Dashboard -> SQL Editor. The application uses raw
-- PostgREST and cannot apply DDL with SUPABASE_URL/SUPABASE_KEY alone.
-- After this migration, run:
--   node --experimental-strip-types scripts/refresh-location-stats.mjs
--
-- Design guarantees:
--   * every scope in a published snapshot shares one cutoff
--   * a refresh is one database transaction
--   * a failure rolls back and leaves the previous published snapshot current
--   * page requests read small rollup rows, never COUNT the 1.9m-row source
--   * v1 geographic matching is transparent curated-term matching; it is not
--     represented as proof of residence

BEGIN;

CREATE TABLE IF NOT EXISTS directory_location_scopes (
  scope_type text NOT NULL
    CHECK (scope_type IN ('national', 'region', 'state', 'city')),
  scope_slug text NOT NULL
    CHECK (scope_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  label text NOT NULL CHECK (btrim(label) <> ''),
  url_slug text,
  parent_state_slug text,
  abbreviation text,
  terms text[] NOT NULL DEFAULT '{}',
  sort_order integer NOT NULL DEFAULT 0,
  enabled boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (scope_type, scope_slug),
  CHECK (scope_type = 'city' OR parent_state_slug IS NULL),
  CHECK (scope_type <> 'city' OR parent_state_slug IS NOT NULL),
  CHECK (scope_type = 'national' OR cardinality(terms) > 0)
);

COMMENT ON TABLE directory_location_scopes IS
  'Versioned input taxonomy for location-stat snapshots. Terms are case-insensitive matches against onlyfans_profiles.location; they are not proof of residence.';

CREATE TABLE IF NOT EXISTS directory_stats_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cutoff_at timestamptz NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  content_changed_at timestamptz,
  status text NOT NULL DEFAULT 'building'
    CHECK (status IN ('building', 'complete')),
  is_published boolean NOT NULL DEFAULT false,
  methodology_version text NOT NULL,
  freshness_window_days smallint NOT NULL DEFAULT 30
    CHECK (freshness_window_days = 30),
  source_profile_count bigint,
  scope_count integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (status = 'building' AND completed_at IS NULL AND is_published = false)
    OR (status = 'complete' AND completed_at IS NOT NULL)
  ),
  CHECK (is_published = false OR status = 'complete')
);

-- At most one fully built snapshot is visible. The refresh function flips this
-- flag only after every requested scope has been inserted successfully.
CREATE UNIQUE INDEX IF NOT EXISTS directory_stats_one_published_idx
  ON directory_stats_snapshots (is_published)
  WHERE is_published;

CREATE INDEX IF NOT EXISTS directory_stats_completed_cutoff_idx
  ON directory_stats_snapshots (cutoff_at DESC)
  WHERE status = 'complete';

CREATE TABLE IF NOT EXISTS directory_location_stats (
  snapshot_id bigint NOT NULL
    REFERENCES directory_stats_snapshots(id) ON DELETE CASCADE,
  scope_type text NOT NULL,
  scope_slug text NOT NULL,
  label text NOT NULL,
  url_slug text,
  parent_state_slug text,
  abbreviation text,
  sort_order integer NOT NULL DEFAULT 0,

  active_count bigint NOT NULL CHECK (active_count >= 0),
  verified_count bigint NOT NULL CHECK (verified_count >= 0),
  free_count bigint NOT NULL CHECK (free_count >= 0),
  paid_count bigint NOT NULL CHECK (paid_count >= 0),
  price_known_count bigint NOT NULL CHECK (price_known_count >= 0),
  median_paid_price double precision,
  paid_price_p25 double precision,
  paid_price_p75 double precision,

  new_7d_count bigint NOT NULL CHECK (new_7d_count >= 0),
  new_30d_count bigint NOT NULL CHECK (new_30d_count >= 0),
  refreshed_7d_count bigint NOT NULL CHECK (refreshed_7d_count >= 0),
  refreshed_30d_count bigint NOT NULL CHECK (refreshed_30d_count >= 0),
  checked_30d_count bigint NOT NULL CHECK (checked_30d_count >= 0),
  successful_checked_30d_count bigint NOT NULL
    CHECK (successful_checked_30d_count >= 0),
  recently_seen_30d_count bigint NOT NULL
    CHECK (recently_seen_30d_count >= 0),
  content_known_count bigint NOT NULL CHECK (content_known_count >= 0),

  total_posts bigint NOT NULL CHECK (total_posts >= 0),
  total_photos bigint NOT NULL CHECK (total_photos >= 0),
  total_videos bigint NOT NULL CHECK (total_videos >= 0),
  total_media bigint NOT NULL CHECK (total_media >= 0),
  source_latest_refresh_at timestamptz,
  content_changed_at timestamptz NOT NULL,

  PRIMARY KEY (snapshot_id, scope_type, scope_slug),
  FOREIGN KEY (scope_type, scope_slug)
    REFERENCES directory_location_scopes(scope_type, scope_slug),
  CHECK (verified_count <= active_count),
  CHECK (price_known_count <= active_count),
  CHECK (free_count + paid_count <= price_known_count),
  CHECK (checked_30d_count <= active_count),
  CHECK (successful_checked_30d_count <= checked_30d_count),
  CHECK (recently_seen_30d_count <= active_count),
  CHECK (content_known_count <= active_count)
);

CREATE INDEX IF NOT EXISTS directory_location_stats_scope_history_idx
  ON directory_location_stats (scope_type, scope_slug, snapshot_id DESC);

CREATE INDEX IF NOT EXISTS directory_location_stats_state_cities_idx
  ON directory_location_stats (snapshot_id, parent_state_slug, active_count DESC)
  WHERE scope_type = 'city';

COMMENT ON TABLE directory_location_stats IS
  'Exact rollups computed from current onlyfans_profiles rows at one immutable cutoff. Sponsored placement configuration does not affect any metric.';
COMMENT ON COLUMN directory_location_stats.active_count IS
  'isperformer=true, status=active, nonblank location, and a curated case-insensitive scope-term match.';
COMMENT ON COLUMN directory_location_stats.price_known_count IS
  'Effective price is coalesce(currentsubscribeprice, subscribeprice); NULL and negative values are unknown.';
COMMENT ON COLUMN directory_location_stats.free_count IS
  'Effective advertised subscription price equals zero among active, price-known profiles.';
COMMENT ON COLUMN directory_location_stats.median_paid_price IS
  'Median effective price strictly above zero. Free and unknown prices are excluded.';
COMMENT ON COLUMN directory_location_stats.content_known_count IS
  'Active matched profiles with at least one non-null post, photo, video, or media source counter.';
COMMENT ON COLUMN directory_location_stats.total_media IS
  'Sum of nonnegative current mediascount values; source media counters may overlap other content counters.';

CREATE OR REPLACE FUNCTION refresh_directory_location_stats(
  p_scopes jsonb,
  p_cutoff timestamptz DEFAULT now(),
  p_methodology_version text DEFAULT 'location-stats-v1',
  p_freshness_window_days integer DEFAULT 30
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET statement_timeout = '15min'
AS $$
DECLARE
  v_snapshot_id bigint;
  v_scope_count integer;
  v_completed_at timestamptz;
BEGIN
  -- Only one potentially expensive rebuild may run at a time. The transaction
  -- lock disappears automatically on success, error, disconnect, or timeout.
  PERFORM pg_advisory_xact_lock(hashtextextended('directory-location-stats-v1', 0));

  IF p_methodology_version <> 'location-stats-v1' THEN
    RAISE EXCEPTION 'Unsupported methodology version: %', p_methodology_version;
  END IF;
  IF p_freshness_window_days <> 30 THEN
    RAISE EXCEPTION 'location-stats-v1 requires a 30-day freshness window';
  END IF;
  IF p_cutoff IS NULL
    OR p_cutoff > now() + interval '5 minutes'
    OR p_cutoff < now() - interval '10 minutes' THEN
    RAISE EXCEPTION 'Snapshot cutoff must be within ten minutes of the transaction start';
  END IF;
  IF jsonb_typeof(p_scopes) IS DISTINCT FROM 'array'
    OR jsonb_array_length(p_scopes) = 0 THEN
    RAISE EXCEPTION 'p_scopes must be a non-empty JSON array';
  END IF;

  CREATE TEMP TABLE incoming_directory_location_scopes (
    scope_type text NOT NULL,
    scope_slug text NOT NULL,
    label text NOT NULL,
    url_slug text,
    parent_state_slug text,
    abbreviation text,
    terms text[] NOT NULL,
    sort_order integer NOT NULL,
    PRIMARY KEY (scope_type, scope_slug)
  ) ON COMMIT DROP;

  INSERT INTO incoming_directory_location_scopes (
    scope_type,
    scope_slug,
    label,
    url_slug,
    parent_state_slug,
    abbreviation,
    terms,
    sort_order
  )
  SELECT
    lower(btrim(x.scope_type)),
    lower(btrim(x.scope_slug)),
    btrim(x.label),
    nullif(lower(btrim(x.url_slug)), ''),
    nullif(lower(btrim(x.parent_state_slug)), ''),
    nullif(upper(btrim(x.abbreviation)), ''),
    ARRAY(
      SELECT DISTINCT lower(btrim(term))
      FROM unnest(coalesce(x.terms, '{}'::text[])) AS term
      WHERE btrim(term) <> ''
      ORDER BY lower(btrim(term))
    ),
    coalesce(x.sort_order, 0)
  FROM jsonb_to_recordset(p_scopes) AS x(
    scope_type text,
    scope_slug text,
    label text,
    url_slug text,
    parent_state_slug text,
    abbreviation text,
    terms text[],
    sort_order integer
  );

  IF EXISTS (
    SELECT 1
    FROM incoming_directory_location_scopes
    WHERE scope_type NOT IN ('national', 'region', 'state', 'city')
      OR scope_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
      OR label = ''
      OR (scope_type <> 'national' AND cardinality(terms) = 0)
      OR EXISTS (
        SELECT 1 FROM unnest(terms) AS term
        WHERE char_length(term) < 3
          OR term LIKE '%\%%' ESCAPE '\'
          OR term LIKE '%\_%' ESCAPE '\'
      )
  ) THEN
    RAISE EXCEPTION 'Invalid directory location scope payload';
  END IF;

  IF (SELECT count(*) FROM incoming_directory_location_scopes WHERE scope_type = 'national') <> 1
    OR NOT EXISTS (
      SELECT 1 FROM incoming_directory_location_scopes
      WHERE scope_type = 'national' AND scope_slug = 'united-states'
    ) THEN
    RAISE EXCEPTION 'Exactly one national:united-states scope is required';
  END IF;

  IF (SELECT count(*) FROM incoming_directory_location_scopes WHERE scope_type = 'state') <> 50 THEN
    RAISE EXCEPTION 'location-stats-v1 requires all 50 state scopes';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM incoming_directory_location_scopes city
    WHERE city.scope_type = 'city'
      AND (
        city.parent_state_slug IS NULL
        OR NOT EXISTS (
          SELECT 1
          FROM incoming_directory_location_scopes state
          WHERE state.scope_type = 'state'
            AND state.scope_slug = city.parent_state_slug
        )
      )
  ) THEN
    RAISE EXCEPTION 'Every city must reference a supplied state scope';
  END IF;

  -- Keep the taxonomy and snapshot inputs in the same transaction. Removed
  -- config scopes remain in history but cannot accidentally enter a new run.
  UPDATE directory_location_scopes SET enabled = false, updated_at = now();

  INSERT INTO directory_location_scopes (
    scope_type,
    scope_slug,
    label,
    url_slug,
    parent_state_slug,
    abbreviation,
    terms,
    sort_order,
    enabled,
    updated_at
  )
  SELECT
    scope_type,
    scope_slug,
    label,
    url_slug,
    parent_state_slug,
    abbreviation,
    terms,
    sort_order,
    true,
    now()
  FROM incoming_directory_location_scopes
  ON CONFLICT (scope_type, scope_slug) DO UPDATE SET
    label = EXCLUDED.label,
    url_slug = EXCLUDED.url_slug,
    parent_state_slug = EXCLUDED.parent_state_slug,
    abbreviation = EXCLUDED.abbreviation,
    terms = EXCLUDED.terms,
    sort_order = EXCLUDED.sort_order,
    enabled = true,
    updated_at = now();

  SELECT count(*) INTO v_scope_count
  FROM incoming_directory_location_scopes;

  INSERT INTO directory_stats_snapshots (
    cutoff_at,
    methodology_version,
    freshness_window_days,
    scope_count
  ) VALUES (
    p_cutoff,
    p_methodology_version,
    p_freshness_window_days,
    v_scope_count
  )
  RETURNING id INTO v_snapshot_id;

  -- All scopes are aggregated by one SQL statement. Under PostgreSQL's default
  -- READ COMMITTED isolation, separate loop statements can see writes committed
  -- between states; one statement gives every scope the exact same MVCC source
  -- snapshot while still allowing the location trigram index to serve matches.
  WITH inserted_stats AS (
    INSERT INTO directory_location_stats (
    snapshot_id,
    scope_type,
    scope_slug,
    label,
    url_slug,
    parent_state_slug,
    abbreviation,
    sort_order,
    active_count,
    verified_count,
    free_count,
    paid_count,
    price_known_count,
    median_paid_price,
    paid_price_p25,
    paid_price_p75,
    new_7d_count,
    new_30d_count,
    refreshed_7d_count,
    refreshed_30d_count,
    checked_30d_count,
    successful_checked_30d_count,
    recently_seen_30d_count,
    content_known_count,
    total_posts,
    total_photos,
    total_videos,
    total_media,
    source_latest_refresh_at,
    content_changed_at
  )
  WITH state_patterns AS (
    SELECT array_agg(DISTINCT '%' || term || '%') AS patterns
    FROM incoming_directory_location_scopes state,
      unnest(state.terms) AS term
    WHERE state.scope_type = 'state'
  ),
  scope_patterns AS (
    SELECT
      scope.*,
      CASE
        WHEN scope.scope_type = 'national' THEN state_patterns.patterns
        ELSE ARRAY(
          SELECT '%' || term || '%'
          FROM unnest(scope.terms) AS term
          ORDER BY term
        )
      END AS patterns
    FROM incoming_directory_location_scopes scope
    CROSS JOIN state_patterns
  ),
  matched AS (
    SELECT
      scope.scope_type,
      scope.scope_slug,
      scope.label,
      scope.url_slug,
      scope.parent_state_slug,
      scope.abbreviation,
      scope.sort_order,
      p.id,
      p.isverified,
      coalesce(p.currentsubscribeprice, p.subscribeprice) AS effective_price,
      p.first_seen_at,
      p.last_refreshed_at,
      p.last_checked_at,
      p.last_check_http_status,
      p.last_seen_at,
      p.lastseen,
      p.postscount,
      p.photoscount,
      p.videoscount,
      p.mediascount
    FROM scope_patterns scope
    LEFT JOIN onlyfans_profiles p
      ON p.isperformer IS TRUE
      AND p.status = 'active'
      AND nullif(btrim(p.location), '') IS NOT NULL
      AND p.location ILIKE ANY (scope.patterns)
  )
  SELECT
    v_snapshot_id,
    scope_type,
    scope_slug,
    label,
    url_slug,
    parent_state_slug,
    abbreviation,
    sort_order,
    count(id),
    count(*) FILTER (WHERE id IS NOT NULL AND isverified IS TRUE),
    count(*) FILTER (WHERE id IS NOT NULL AND effective_price = 0),
    count(*) FILTER (WHERE id IS NOT NULL AND effective_price > 0),
    count(*) FILTER (WHERE id IS NOT NULL AND effective_price >= 0),
    percentile_cont(0.50) WITHIN GROUP (ORDER BY effective_price)
      FILTER (WHERE id IS NOT NULL AND effective_price > 0),
    percentile_cont(0.25) WITHIN GROUP (ORDER BY effective_price)
      FILTER (WHERE id IS NOT NULL AND effective_price > 0),
    percentile_cont(0.75) WITHIN GROUP (ORDER BY effective_price)
      FILTER (WHERE id IS NOT NULL AND effective_price > 0),
    count(*) FILTER (
      WHERE id IS NOT NULL
        AND first_seen_at >= p_cutoff - interval '7 days'
        AND first_seen_at <= p_cutoff
    ),
    count(*) FILTER (
      WHERE id IS NOT NULL
        AND first_seen_at >= p_cutoff - interval '30 days'
        AND first_seen_at <= p_cutoff
    ),
    count(*) FILTER (
      WHERE id IS NOT NULL
        AND last_refreshed_at >= p_cutoff - interval '7 days'
        AND last_refreshed_at <= p_cutoff
    ),
    count(*) FILTER (
      WHERE id IS NOT NULL
        AND last_refreshed_at >= p_cutoff - interval '30 days'
        AND last_refreshed_at <= p_cutoff
    ),
    count(*) FILTER (
      WHERE id IS NOT NULL
        AND last_checked_at >= p_cutoff - interval '30 days'
        AND last_checked_at <= p_cutoff
    ),
    count(*) FILTER (
      WHERE id IS NOT NULL
        AND last_checked_at >= p_cutoff - interval '30 days'
        AND last_checked_at <= p_cutoff
        AND last_check_http_status BETWEEN 200 AND 299
    ),
    count(*) FILTER (
      WHERE id IS NOT NULL
        AND coalesce(last_seen_at, lastseen) >= p_cutoff - interval '30 days'
        AND coalesce(last_seen_at, lastseen) <= p_cutoff
    ),
    count(*) FILTER (
      WHERE id IS NOT NULL
        AND (
          postscount IS NOT NULL
          OR photoscount IS NOT NULL
          OR videoscount IS NOT NULL
          OR mediascount IS NOT NULL
        )
    ),
    coalesce(sum(greatest(coalesce(postscount, 0), 0)) FILTER (WHERE id IS NOT NULL), 0),
    coalesce(sum(greatest(coalesce(photoscount, 0), 0)) FILTER (WHERE id IS NOT NULL), 0),
    coalesce(sum(greatest(coalesce(videoscount, 0), 0)) FILTER (WHERE id IS NOT NULL), 0),
    coalesce(sum(greatest(coalesce(mediascount, 0), 0)) FILTER (WHERE id IS NOT NULL), 0),
    max(last_refreshed_at) FILTER (WHERE id IS NOT NULL),
    p_cutoff
  FROM matched
  GROUP BY
    scope_type,
    scope_slug,
    label,
    url_slug,
    parent_state_slug,
    abbreviation,
    sort_order
  RETURNING snapshot_id
  ),
  source_count AS (
    -- Count the active source rows in the same top-level SQL statement and
    -- therefore the same MVCC snapshot as every geographic aggregate.
    SELECT count(*) AS profile_count
    FROM onlyfans_profiles
    WHERE isperformer IS TRUE
      AND status = 'active'
  )
  UPDATE directory_stats_snapshots snapshot
  SET source_profile_count = source_count.profile_count
  FROM source_count
  WHERE snapshot.id = v_snapshot_id
    AND EXISTS (SELECT 1 FROM inserted_stats);

  v_completed_at := clock_timestamp();

  -- Per-scope content_changed_at advances only when a displayed metric changes.
  -- Rechecking unchanged source rows therefore does not manufacture sitemap
  -- freshness. Rolling-window counts are displayed metrics and are included.
  UPDATE directory_location_stats
  SET content_changed_at = v_completed_at
  WHERE snapshot_id = v_snapshot_id;

  WITH previous AS (
    SELECT DISTINCT ON (old.scope_type, old.scope_slug)
      old.*
    FROM directory_location_stats old
    JOIN directory_stats_snapshots old_snapshot
      ON old_snapshot.id = old.snapshot_id
    WHERE old_snapshot.status = 'complete'
      AND old_snapshot.cutoff_at < p_cutoff
    ORDER BY old.scope_type, old.scope_slug, old_snapshot.cutoff_at DESC
  )
  UPDATE directory_location_stats current
  SET content_changed_at = previous.content_changed_at
  FROM previous
  WHERE current.snapshot_id = v_snapshot_id
    AND current.scope_type = previous.scope_type
    AND current.scope_slug = previous.scope_slug
    AND ROW(
      current.active_count,
      current.verified_count,
      current.free_count,
      current.paid_count,
      current.price_known_count,
      current.median_paid_price,
      current.paid_price_p25,
      current.paid_price_p75,
      current.new_7d_count,
      current.new_30d_count,
      current.refreshed_7d_count,
      current.refreshed_30d_count,
      current.checked_30d_count,
      current.successful_checked_30d_count,
      current.recently_seen_30d_count,
      current.content_known_count,
      current.total_posts,
      current.total_photos,
      current.total_videos,
      current.total_media
    ) IS NOT DISTINCT FROM ROW(
      previous.active_count,
      previous.verified_count,
      previous.free_count,
      previous.paid_count,
      previous.price_known_count,
      previous.median_paid_price,
      previous.paid_price_p25,
      previous.paid_price_p75,
      previous.new_7d_count,
      previous.new_30d_count,
      previous.refreshed_7d_count,
      previous.refreshed_30d_count,
      previous.checked_30d_count,
      previous.successful_checked_30d_count,
      previous.recently_seen_30d_count,
      previous.content_known_count,
      previous.total_posts,
      previous.total_photos,
      previous.total_videos,
      previous.total_media
    );

  UPDATE directory_stats_snapshots
  SET is_published = false
  WHERE is_published;

  UPDATE directory_stats_snapshots
  SET
    status = 'complete',
    completed_at = v_completed_at,
    content_changed_at = (
      SELECT max(content_changed_at)
      FROM directory_location_stats
      WHERE snapshot_id = v_snapshot_id
    ),
    is_published = true
  WHERE id = v_snapshot_id;

  RETURN v_snapshot_id;
END;
$$;

-- This is the only relation application pages read. Thirty-day change is
-- nullable until a complete snapshot at least 30 days older exists.
CREATE OR REPLACE VIEW directory_location_stats_current
WITH (security_invoker = true)
AS
SELECT
  current.snapshot_id,
  snapshot.cutoff_at,
  snapshot.completed_at,
  current.content_changed_at,
  snapshot.methodology_version,
  snapshot.freshness_window_days,
  snapshot.source_profile_count,
  current.scope_type,
  current.scope_slug,
  current.label,
  current.url_slug,
  current.parent_state_slug,
  current.abbreviation,
  current.sort_order,
  current.active_count,
  current.verified_count,
  current.free_count,
  current.paid_count,
  current.price_known_count,
  current.median_paid_price,
  current.paid_price_p25,
  current.paid_price_p75,
  current.new_7d_count,
  current.new_30d_count,
  current.refreshed_7d_count,
  current.refreshed_30d_count,
  current.checked_30d_count,
  current.successful_checked_30d_count,
  current.recently_seen_30d_count,
  current.content_known_count,
  current.total_posts,
  current.total_photos,
  current.total_videos,
  current.total_media,
  current.source_latest_refresh_at,
  previous.cutoff_at AS previous_cutoff_at,
  CASE
    WHEN previous.active_count IS NULL THEN NULL
    ELSE current.active_count - previous.active_count
  END AS change_30d_count,
  CASE
    WHEN previous.active_count IS NULL OR previous.active_count = 0 THEN NULL
    ELSE round(
      100.0 * (current.active_count - previous.active_count)::numeric
        / previous.active_count::numeric,
      2
    )::double precision
  END AS change_30d_percent
FROM directory_location_stats current
JOIN directory_stats_snapshots snapshot
  ON snapshot.id = current.snapshot_id
  AND snapshot.status = 'complete'
  AND snapshot.is_published
LEFT JOIN LATERAL (
  SELECT
    old_snapshot.cutoff_at,
    old.active_count
  FROM directory_location_stats old
  JOIN directory_stats_snapshots old_snapshot
    ON old_snapshot.id = old.snapshot_id
  WHERE old.scope_type = current.scope_type
    AND old.scope_slug = current.scope_slug
    AND old_snapshot.status = 'complete'
    AND old_snapshot.cutoff_at <= snapshot.cutoff_at - interval '30 days'
  ORDER BY old_snapshot.cutoff_at DESC
  LIMIT 1
) previous ON true;

COMMENT ON VIEW directory_location_stats_current IS
  'The one fully published location-stat snapshot, plus a nullable at-least-30-day comparison. Empty means unavailable, never zero.';

REVOKE ALL ON TABLE directory_location_scopes FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE directory_stats_snapshots FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE directory_location_stats FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE directory_location_stats_current FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION refresh_directory_location_stats(jsonb, timestamptz, text, integer)
  FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE directory_location_stats_current TO service_role;
-- security_invoker views check the caller's privileges on their base tables.
GRANT SELECT ON TABLE directory_stats_snapshots TO service_role;
GRANT SELECT ON TABLE directory_location_stats TO service_role;
GRANT EXECUTE ON FUNCTION refresh_directory_location_stats(jsonb, timestamptz, text, integer)
  TO service_role;

COMMIT;
